/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hexaberry_soda_cans_DRACO.glb 
Author: hexabear2020 (https://sketchfab.com/hexabear2020)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hexaberry-soda-cans-96aa6a20264848ab9c5be2478594ec44
Title: HexaBerry Soda Cans
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

export default function HexaBerryCan5({scale, position, ...props}) {
  const { nodes, materials } = useGLTF('./models/hexaberry_soda_cans_DRACO.glb')
  return (
    <e.group theatreKey='HexbBerryCan5' scale={scale} position={position} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -1.429]} scale={9.104}>
        <mesh geometry={nodes.Soda_5_Metal004_0.geometry} material={materials['Metal.004']} />
        <mesh geometry={nodes.Soda_5_Soda004_0.geometry} material={materials['Soda.004']} />
      </group>
    </e.group>
  )
}

useGLTF.preload('/hexaberry_soda_cans_DRACO.glb')
